### ISSUE TITLE
サイトデザインやるかもメモ

### ISSUE THREAD

**Issue by mwrote** [trkw/tubalcain#164]
久しぶりにデザインやりたいので、@trkw に負けないようデザインでもモダンな感じにしたい

## やること

- ロゴ
- フォント選定
- サイトデザイン…これはCSSコーディングしながらデザインする。効率重視で
- hightlight.js用のcss (できれば)

### サイト名

わかりやすい、覚えやすい、短い、ドメインとれるやつ、trkwは覚えにくいw
↓ちょっと考えてみた
  - Bonnet WEB … フロントエンドはありきたりなので車に例えてボンネット。comとnet以外はとれる

## 個人的にやりたいこと

- gfm準拠のセンスある感じで読みやすい md or org のCSSセット作りたい←その部分だけ別リポジトリでライブラリ化して公開したいかも。hightlight.jsと組み合わせてよりコーダー向けにオシャレに
- ポイントでセンスのある小さなアニメーション入れたい。[CreativeApplicationsのロゴ](http://www.creativeapplications.net/)とか[これ](http://nardove.com/)とか。みためだけで勝負より、やっぱりアニメコーディングで差別化したい

**Comment by trkw** [comment]
@mwrote 
> 寺川さんに負けないようデザインでもモダンな感じにしたい

僕も負けないよ！

**Comment by mwrote** [comment]
@trkw 
とあえずサイト名決めないとね、trkwがいい？

**Comment by miyaoka** [comment]
老舗料亭っぽく、とり川 って名前にしてた時期もありました。方向性が迷走

**Comment by mwrote** [comment]
とり川w ちょっとモダンっぽくしずらいなぁ〜

**Comment by trkw** [comment]
@miyaoka @mwrote とりあえずの「と」とか言ってた時期もありました。
でも、もう名前変えちゃっていいかも。
でリポジトリも再度作り直すかしようよ。

**Comment by trkw** [comment]
名前を変えるってだけであれば、組織作らないで、ここでリポジトリの名前変えるだけでいいよ

**Comment by trkw** [comment]
サイト名提案

もう命名するなら、中二病全開で意味とかいらない。
WEBとかいらない。
神がいい。

Category:ギリシア神話の神
https://ja.wikipedia.org/wiki/Category:%E3%82%AE%E3%83%AA%E3%82%B7%E3%82%A2%E7%A5%9E%E8%A9%B1%E3%81%AE%E7%A5%9E

「夢」にまつわる世界各地の伝説や神話7つ 
http://estorypost.com/trivia/seven-legends-about-dreams/

例:
phobetor.jp
phobetor.io

**Comment by mwrote** [comment]
> でも、もう名前変えちゃっていいかも。
> でリポジトリも再度作り直すかしようよ。

そのあたりは何がベストかよくわからないので、まかす
サイト作り直すなら既存のCSSは全部消したいぐらい

> 神がいい。

いいんじゃん、俺もそっち系すきだし

**Comment by mwrote** [comment]
phobetorはちょっと発音しずらいなぁ
発音しやすいやつがいい

**Comment by trkw** [comment]
http://postcss.org/
http://www.nightmarejs.org/

こういう意味の分からないけど、皇后しい感じにしたい

**Comment by trkw** [comment]
@mwrote Chronus とかは？

**Comment by mwrote** [comment]
@trkw 
chronusいいけどドメインtokyoしかないね
俺的にはtubalcain(トバルカイン)がいい
カインの子で「鍛冶の祖」と言われてる、
WEBのツール(道具)についての話題多いだろうから、思想も合ってない？
postcssともフリーメイソン繋がりだしw

**Comment by trkw** [comment]
@mwrote それいいね！

**Comment by trkw** [comment]
安定のJPドメイン
tubalcain.jp

.inとなんか合わせる感じ
tubalca.in

技術者として.io？
tubalcain.io

**Comment by mwrote** [comment]
tubalcain.ioかな〜
コンセプトが一言でいい表されている気がする
3つどれもいいけどね〜

1つ目は無難だよね、ただ一見トバルカイン好きな日本人wにも捉えられがち
2つ目は面白いけど、開発していくなかでいろいろ面倒くさそう、あとfamo.usってライブラリはやったときに結局頭に残ってたのはfamoだったからなぁ、となるとtubalcaになっちゃうし
3つ目は特に不満点ないし、合ってる

**Comment by trkw** [comment]
tubalcainっていうgithubの組織とられてる…

**Comment by mwrote** [comment]
:rage4:

**Comment by mwrote** [comment]
じゃあtrkwのリポジトリでいいじゃん
もしくはtubal-cain?
wikiだとtubal-cainだね
https://en.wikipedia.org/wiki/Tubal-cain

**Comment by trkw** [comment]
wikiに合わせるか

**Comment by mwrote** [comment]
うん、いたしかたない

**Comment by trkw** [comment]
tubal-cainも取れないな。

**Comment by mwrote** [comment]
:rage4:

**Comment by trkw** [comment]
.io	9,962円

高いんだよね。

**Comment by trkw** [comment]
.in	1,980円
.jp（ローマ字）	2,840円
.co	899円

**Comment by mwrote** [comment]
高いね、じぁあjpにしよう。いつか割り勘分おごるよw

**Comment by mwrote** [comment]
俺はどれでもいいよ、リポジトリも
検索上位に上がれればどれでも関係ないだろうから、お任せします

**Comment by trkw** [comment]
phenomicをリスペクトして、trkw/tubalcainにしておくか。

**Comment by miyaoka** [comment]
jpそんなに安いんだっけ？
昔は年額1万してたような

**Comment by trkw** [comment]
@miyaoka 継続していくと高くなるね。

**Comment by trkw** [comment]
ドメインについてはこっちでやろう。
https://github.com/trkw/tubalcain/issues/167

**Comment by trkw** [comment]
一旦、tubalcainでサイト名は決定、デザインで必要な事があったらprojectsから作成していこう
