### ISSUE TITLE
TUBALCAIN サイトデザイン

### ISSUE THREAD

**Issue by mwrote** [trkw/tubalcain#174]
![desktop hd](https://cloud.githubusercontent.com/assets/805577/20101550/d47ce17a-a605-11e6-9c68-38adaac6acb9.png)

まだフィックスじゃないけど、ほぼフィックス。
インパクト重視で!
まだ要素が少ないから、適当に盛り付けてます。
とりあえずこれで許してください。
今後ブラシュアップ、動きとかスクリプトとか入れていってよりモダンにしていきます。
やる気があれば、どこかで大幅ブラシュアップするかも。

直近で考えていること

* ロゴしっかり作る、トバルカイン的なシンボルアイコン作りたい
* スクロールし始めると背景と白に文字黒にアニメーションし、記事が読みやすくなる
* codeタグ用のカラーシンタックスデザイン作成。サイトデザインに同化した、読みやすいやつつくる。

## 素材一覧

* 画像引用元　http://www.everystockphoto.com/photo.php?imageId=8586844&searchId=59418a4bb16c7b1d458713ea2bb222b0&npos=1
* アイコンはすべて http://fontawesome.io/ 。Webフォントなので記事に応じてタイトル部分に好きなアイコン入れれる
* 基本フォントは [Myrica](https://myrica.estable.jp/)。源ノゴシックとかInconsolataとかフリーフォントごちゃまぜのプログラミング用合成フォント。そのままでは重いので、サブセット化して軽くする。
本文でも使ってるけど、codeタグ部分にこのフォント使う予定。本文とcode部分を綺麗に同化させる。
* ロゴの部分だけ Futuraフォント、これは有料フォントなので、SVGにしてちょっといじってロゴとして使う
## リソース

* http://helvetinote.com/ まぁ結構オマージュしてます。色変えて表現かぶらないようふってくかも

## リクエスト求む

みんなOKだったらissue閉じる。ただ力尽きたので、現在あまり修正する気力はない

**Comment by mwrote** [comment]
@trkw
作ったよ。褒めて

**Comment by trkw** [comment]
たけぇｗ

**Comment by trkw** [comment]
これ日本語のフォントなんてフォントなの？

**Comment by trkw** [comment]
@mwrote designのファイルもgithubで管理したいー

**Comment by mwrote** [comment]
@trkw 
とりあえずzipしたsketchファイルあげるね、
[tubalcain.zip](https://github.com/trkw/tubalcain/files/578430/tubalcain.zip)
myrica は無料フォントだからOKだけど Futura使ってるからその部分だけ正しく表示されないよ
レイヤーとか綺麗にしてないからgit管理はちょっと待ってほしい、一応Atomic Designでファイル作る予定なので

**Comment by trkw** [comment]
@mwrote Myrica ほう。

**Comment by mwrote** [comment]
@miyaoka
これからモダン目指してきますw

**Comment by trkw** [comment]
プログラミングフォントはMonacoが好きなんだよな

http://hivelogic.com/articles/top-10-programming-fonts/

**Comment by mwrote** [comment]
フォントはラインセンス調べないとだね(Myricaもまだちゃんと調べてない)、
Monacoでもいいけど、日本語のフォントを組み合わせてきれいに見えれば俺はOKだよ
まぁcode要素内には日本語入れないってなら特に問題はないけど
ライセンスも問題なくて、きれいで日本語もOKな等幅フォントあれば情報求む
フォントはサイトの印象大きく左右する重要な要素なので

**Comment by mwrote** [comment]
ちなみに個人的には Source Code Pro が好き。
https://fonts.google.com/specimen/Source+Code+Pro
がんばれば好きなフォント合成して自分で作れるけど、それはそれで時間かかる

**Comment by trkw** [comment]
Myricaのライセンスは SIL OPEN FONT LICENSE Version 1.1
日本語訳は下記
https://ja.osdn.net/projects/opensource/wiki/SIL_Open_Font_License_1.1

**Comment by mwrote** [comment]
Myricaはあくまで素人が色んなフォント組み合わせましたってだけだから、ちょっと信用はできないんよ
中で使っているフォントすべてのライセンスみたしてるか作者に聞いてみないとわからん、まぁたぶん問題は起こらないだろうけど
フォントは知ってると思うけど色々めんどくさいんだよね

**Comment by mwrote** [comment]
@trkw てり川総帥のジャッジメントOKだったのでクローズします

**Comment by trkw** [comment]
テンキュー 😶
