### ISSUE TITLE
robots.txt, humans.txtを配置する

### ISSUE THREAD

**Issue by miyaoka** [trkw/tubalcain#29]

**Comment by trkw** [comment]
humans.txt自由すぎてフォーマット定まらないな。

**Comment by trkw** [comment]
/* the humans responsible & colophon */
/* humanstxt.org */

/* TEAM */
	Editor: @trkw, @miyaoka
	Twitter: @trkw
	Location: Tokyo, Japan

/* SITE */
	Name: trkw
	URL: http://trkw.me
	Contents: OSS Blog
	Standards: HTML, CSS, JavaScript
	Language: Japanese
	Last update: 2016/09/20

**Comment by trkw** [comment]
こういう感じかな？

**Comment by trkw** [comment]
robots.txt

https://syncer.jp/how-to-setting-robots-txt

へぇ魚拓とかブロックできるんだね、知らなかった。
