### ISSUE TITLE
post内のscriptタグが無効化されるのを有効化したい

### ISSUE THREAD

**Issue by miyaoka** [trkw/tubalcain#35]
<s>twitterやflickrのembed時にscriptタグがついてくるが、dangerouslySetInnerHTMLあたりで無効化されてしまう模様<s>

**Comment by miyaoka** [comment]
buildするとTwitterのは有効になるけどFlickrのはだめだなー

**Comment by miyaoka** [comment]
Post内ではTwitterがちゃんと表示されてたのは、SNSボタンモジュールを入れてからtwitterのスクリプトがそこで読み込まれていたから。

で、問題としてはmarkdownを通過するとただの平文になってしまうことで、これはPhenomicではなくmarkdown自体の問題。対処法としては

- Phenomicのプラグインを作ってwebpack.configに設定
- 本文からscriptタグ内のsrc部分のURLを抽出
- ヘッダのプロパティに格納
- WebModule内でヘッダからimport

でいけるぽい。

（ページのdescriptonなどはこの手順でヘッダに情報を格納してる）

**Comment by trkw** [comment]
とりあえず、phenomicのバージョンがあがってるので一旦クローズ
