### ISSUE TITLE
テーマカラーとアクセントカラーを決める

### ISSUE THREAD

**Issue by miyaoka** [trkw/tubalcain#52]
マテリアルデザインのサイトで選べる

**Comment by miyaoka** [comment]
https://getmdl.io/customize/index.html
![fireshot capture 6 - material design lite - https___getmdl io_customize_index html](https://cloud.githubusercontent.com/assets/1443118/18253235/0c082c36-73ce-11e6-9fb4-6daaa4d33350.png)

こんなの

**Comment by trkw** [comment]
デザインを @mwrote に依頼するため、
一旦クローズ、なにかあればprojectsからissueを作成
