### ISSUE TITLE
トップページの文言を整える

### ISSUE THREAD

**Issue by miyaoka** [trkw/tubalcain#73]

**Comment by trkw** [comment]
トップページで伝えたいこと。

タイトル トリカワ
詳細 このサイトは、phenomicによって作成された共同サイトです。

phenomicとはこのような技術で出来ています。

react webpack

コントリビューター
trkw, miyaoka

アーカイブ
記事のリストを表示

**Comment by trkw** [comment]
共同ブログというとなんか違う気がするんだな。

**Comment by miyaoka** [comment]
オープンソースブログとか？

**Comment by trkw** [comment]
meta考える

**Comment by trkw** [comment]
トップページのキャチは、問いかける感じの名言がランダムで出るといいと思うがどうだろうか？
それとも記事のタイトルとか。

**Comment by trkw** [comment]
デザインな話なので一旦クローズ
